import sqlite3

db_path = r"C:\Users\admin\.gemini\antigravity\brain\6776ae56-d1c4-4149-9279-1f3eb725967a\scratch\dental_bot.db"
conn = sqlite3.connect(db_path)
c = conn.cursor()

q101_200_exps = {
    101: 'Miller\'s Chemico-Parasitic Theory (1890) proposed that dental caries is caused by acid produced by acidogenic oral micro-organisms fermenting carbohydrates.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 20)',
    102: 'Traumatized teeth under occlusal trauma show bone resorption, hypercementosis, triangulation, and sometimes pulp necrosis (All of the above).\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 183)',
    103: 'A 3/4 partial veneer crown provides the most retentive conservative form for an anterior bridge retainer.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 125)',
    104: 'Extension of the neck opens the airway and would not cause an airway obstruction, unlike neck flexion or laryngeal muscle paralysis.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 55)',
    105: 'Localized osteitis (dry socket) is characterized by premature fibrinolysis and dissolution of the blood clot.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 88)',
    106: 'According to the SLOB rule (Same Lingual, Opposite Buccal), if the canine moves distally (same direction as tube), it is palatally (lingual) impacted.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 260)',
    108: 'The SNA angle on a cephalometric radiograph signifies the anteroposterior relationship of the Maxilla to the cranial base.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 269)',
    109: 'For a primary tooth with traumatic exposure presenting after 2 days, pulp necrosis is likely and a pulpectomy is indicated.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 234)',
    110: 'Idiopathic failure of eruption with a large gingival bulge and developed root is managed by surgical soft tissue exposure.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 222)',
    111: 'Lactobacilli concentration (>10^5 CFU/ml) in saliva is a strong indicator of high caries activity and active root caries progression.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 22)',
    112: 'Down\'s syndrome is associated with microdontia (small teeth), not macrodontia.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 210)',
    113: 'Squamous cell carcinoma (epidermoid carcinoma) is by far the most common primary malignant tumor of the oral cavity.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 195)',
    114: 'Idiopathic failure of eruption is managed by surgical soft tissue exposure to allow natural eruption.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 222)',
    115: 'Widespread gingivitis, bleeding, and general malaise in a child suggests acute leukemia; refer for immediate hematological screening.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 154)',
    116: 'Regular 6-month office dental prophylaxis provides only a short-term improvement in oral hygiene if not reinforced at home.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 30)',
    117: 'Plaque is considered an infection because it represents organized pathogenic bacterial activity causing tissue destruction.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 182)',
    118: 'Vigorous mastication increases salivary flow and buffering capacity, raising plaque pH and reducing decay.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 24)',
    119: 'Alveolar abscess treatment requires incision and drainage (either through pulp chamber access or soft tissue incision) to relieve pressure.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 212)',
    120: 'Streptococcus mutans synthesizes sticky extracellular glucans (dextrans) specifically from sucrose.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 23)',
    121: 'Water fluoridation decreases dental decay by approximately 45% to 55% in the community.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 28)',
    122: 'Due to peripheral burnout and enamel overlap, proximal caries appear smaller on radiographs than their actual clinical size.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 132)',
    123: 'A fractured cusp immediately adjacent to a class II inlay is typically diagnosed via history of pain on release of biting pressure.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 112)',
    124: 'Softened root cementum should be gently scraped (debrided) and treated with topical fluoride to promote remineralization.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 25)',
    125: 'Missing lateral incisor in Class II Div II is best restored with a fixed bridge using the central incisor and first premolar (bicuspid).\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 126)',
    126: 'Repairing a lower complete denture fracture carries a possibility of occlusal disharmony due to slight assembly errors.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 147)',
    127: 'An electrical pulp tester (vitalometer) checks pulp response to an electrical stimulant to help reveal potential necrosis.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 202)',
    128: 'For Class III composite restorations, acid etching of enamel should always be performed to minimize marginal microleakage.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 92)',
    129: 'Tooth translucency can be lost due to pulp death, complete calcification of the chamber, hyperemia, or pulp stones (All of the above).\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 203)',
    130: 'Self-tapping threaded pins are mechanically screwed into dentin, proving to be the most retentive pin system.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 118)',
    131: 'Reconstructing the occlusal anatomy is based primarily on functional factors (occlusion, guidance, and contact points).\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 142)',
    132: 'The floor of the pulp chamber in molars should be gently swabbed and dried with cotton wool, and remaining pulp excavated.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 210)',
    133: 'Composite resin restorations are finished immediately after curing using fine diamonds and abrasive discs under water.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 94)',
    134: 'Café au lait spots are classic dermatological markers seen in Neurofibromatosis Type 1 (Recklinghausen\'s disease).\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 182)',
    135: 'Von Willebrand disease is a hereditary hemorrhagic (bleeding) disorder caused by deficiency or dysfunction of vWF.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 92)',
    136: 'The extraction of permanent first molars typically employs buccal movement to expand the thinner buccal cortical plate.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 82)',
    137: 'Pethidine is strictly contraindicated with Monoamine Oxidase Inhibitors (MAOIs) due to the risk of severe hyperpyrexic crises.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 102)',
    138: 'A heavy blow to one side of the mandible often causes a direct fracture at that site, and an indirect subcondylar fracture on the opposite side.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 98)',
    139: 'The most common fracture site of Class II amalgam restorations is at the narrow isthmus due to insufficient preparation depth.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 114)',
    140: 'Composite resins show less shrinkage, less surface erosion, and less water absorption than silicate resins (All of the above).\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 92)',
    141: 'The setting expansion of casting investment material is approximately 0.1% to 0.5% to help compensate for metal contraction.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 128)',
    142: 'The volumetric contraction of gold alloys upon solidification is approximately 1.40%.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 129)',
    143: 'Self-cured (cold-cure) acrylic resins typically contain approximately 2.5% residual unpolymerized monomer.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 146)',
    144: 'Polymerization of methyl methacrylate monomer results in a volumetric shrinkage of approximately 21%.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 147)',
    145: 'Fibrous dysplasia is managed by complete excision for small areas, or limited conservative excision for large lesions due to cosmetic concerns.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 156)',
    146: 'The primary treatment for central giant cell granulomas of the jaws is thorough surgical curettage.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 158)',
    147: 'Moisture (oil or water) on impression trays before pouring gypsum causes a significant decrease in the quality of the treatment cast.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 132)',
    148: 'The Path of Insertion is the specific direction of movement of the appliance from initial contact with teeth to its final seat.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 156)',
    149: 'The Path of Removal is the movement of the appliance from its terminal rest position to the last contact of its rigid parts with teeth.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 157)',
    150: 'Recontouring of the occlusal surface must follow original tooth anatomy and should not leave flat surfaces, preserving natural sluiceways.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 154)',
    151: 'The floor of the occlusal rest seat must be spoon-shaped or concave, sloping slightly toward the center of the tooth to direct forces along its long axis.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 156)',
    152: 'Tensile stress transferred to alveolar bone through periodontal ligament fibers promotes bone deposition and maintenance.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 162)',
    153: 'Surveying identifies guide planes, undercuts, interference and support; blockout areas themselves are decided and executed after surveying.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 159)',
    154: 'Guiding planes establish a single path of insertion and withdrawal, ensuring predictable clasp retention and stability.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 157)',
    155: 'Porosity and rough surfaces in dental porcelain are primarily caused by inadequate condensation (lack of compression) before firing.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 102)',
    156: 'The most common cause of failure in metal-ceramic (porcelain-to-metal) restorations is improper metal framework design.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 124)',
    157: 'Setting time of glass ionomer cement can be prolonged by cooling down the mixing glass slab before mixing.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 90)',
    158: 'When restoring a missing maxillary canine, a cantilever bridge should utilize both premolars for adequate support.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 126)',
    160: 'The primary indication to replace missing anterior teeth using a fixed bridge instead of a partial denture is aesthetics.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 125)',
    161: 'Hard gold alloy (Type III) is the gold casting alloy of choice for fabricating crowns and fixed bridges.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 128)',
    162: 'Applying topical fluoride to root surfaces is intended to protect exposed dentin and cementum from root caries.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 25)',
    163: 'When a patient complains of pain under a newly fitted denture, the occlusion must be checked first as it is the most common cause.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 142)',
    164: 'The fovea palatini are landmarks located near the midline of the palate used to determine the posterior post dam border.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 136)',
    165: 'Attrition is defined as the physiological wear of dental hard tissues resulting from tooth-to-tooth contact.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 202)',
    166: 'The modulus of elasticity is a measure of material stiffness, defined as the stress-strain ratio within the proportional limit.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 82)',
    167: 'Tissue conditioning materials (silicone soft liners) are significantly more resilient than standard hard plastic acrylic.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 142)',
    168: 'The most common cause of root canal treatment failure is incomplete obturation (short filling of the canal).\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 214)',
    169: 'During setup of teeth, the crown of the maxillary first premolar is tipped mesially from an occlusal view.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 138)',
    170: 'Lateral and accessory root canals are most commonly located in the apical third of the tooth root.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 210)',
    172: 'Transillumination uses a bright light source through dental tissues to detect dental caries and fractures.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 202)',
    173: 'Squamous cell carcinoma is the most common primary malignant epithelial neoplasm of the oral cavity.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 195)',
    174: 'Replantation of an avulsed tooth after 2.5 hours carries a very high risk of replacement resorption (ankylosis) and external resorption.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 258)',
    175: 'Emergency management for a painless necrotic pulp consists of drainage through the root canal system to relieve subclinical pressure.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 212)',
    176: 'Acute swelling and pain days after obturation is primarily caused by entrapped bacteria proliferating in the periapical region.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 214)',
    177: 'Before placing GIC, dentin should be treated with a dentin conditioner (10% polyacrylic acid) to clean the surface.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 90)',
    178: 'The first step in treating active dental erosion is debriding/polishing with pumice and water before restorative placement.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 25)',
    180: 'Polishing natural teeth before seating an RPD is critical to increase the adaptability and fit of the occlusal rests.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 156)',
    181: 'During lateral movements, artificial teeth in partial dentures should have a slight touch on the balancing side to maintain stability.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 142)',
    182: 'Polyvinyl siloxane (addition silicone) impression materials are the most dimensionally stable elastomeric materials.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 130)',
    183: 'To safely remove pulp tissue from a very narrow or curved canal, a small K-type file is preferred over a barbed broach.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 210)',
    184: 'Wax patterns should not be left on the bench for long periods to avoid dimensional distortion from stress relaxation.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 129)',
    185: 'The ideal undercut depth required for a Cobalt-Chromium retentive cast clasp arm is 0.25mm.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 156)',
    188: 'Both statements are true: Gold clasps are more elastic than Co-Cr, but Co-Cr has a higher modulus of elasticity (stiffness).\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 156)',
    189: 'Abutment teeth selected for overdentures are ideally canines and premolars due to their long root surface area and arch position.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 150)',
    190: 'Taking another periapical radiograph at a different horizontal angulation helps disclose additional overlapping canals or roots.\n\n🏛️ Book Reference: Master Dentistry Vol. 1 (p. 120)',
    191: 'The ideal working length for canal obturation is 0.5 to 1.5 mm short of the radiographic apex (at the apical constriction).\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 214)',
    192: 'The retentive terminal tip of a clasp arm must be positioned below the survey line (in the undercut zone).\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 156)',
    193: 'To minimize occlusal loads on a free-end saddle RPD, select artificial teeth with a narrow buccolingual dimension.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 158)',
    194: 'Retentive clasps are placed such that the flexible clasp arm is located in the gingival third of the tooth crown.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 156)',
    195: 'Internal root resorption of permanent teeth is usually asymptomatic and detected incidentally on routine radiographs.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 203)',
    196: 'Formocresol pulpotomy in primary teeth achieves fixation and mummification of the coronal and radicular pulp tissues.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 234)',
    197: 'Ledermix paste contains a corticosteroid (triamcinolone) which reduces pulpal inflammation and relieves acute pain.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 212)',
    199: 'The technique of compacting gutta-percha laterally against canal walls to create space for accessory cones is lateral condensation.\n\n🏛️ Book Reference: Master Dentistry Vol. 2 (p. 214)'
}

for q_id, exp in q101_200_exps.items():
    c.execute('UPDATE questions SET explanation = ? WHERE id = ?', (exp, q_id))

conn.commit()
conn.close()
print("Successfully enriched Q101-Q200!")
